import type { Metadata } from "next";
import { Mulish } from "next/font/google";
import "./globals.css";
import Providers from "../components/Providers";
import TopNavigation from "@/components/navbar/TopNavigation";

// Fonts
const Moolish = Mulish({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-mulish",
});

// SEO
export const metadata: Metadata = {
  title: "Recycla",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${Moolish.variable}`}>
        <Providers>
          <TopNavigation />
          {children}
        </Providers>
      </body>
    </html>
  );
}
